### ISSUE TITLE
Add confirmation on file transfer overwrite options

### ISSUE THREAD

**Issue by genonullfree** [genonullfree/teleport#34]
Options:

1. Add a flag `-c` to confirm every file that will be overwritten with "y/n" inputs
2. Add a flag `-y` to assume "yes" to overwrite confirmation input

I'm leaning towards 2, because it feels more correct/safe, but 1 keeps the current behavior.

**Comment by CableSynth** [comment]
Why not both?

**Comment by genonullfree** [comment]
I don't think we need this right now. The more I see this ticket, the less I think it's needed. closing
