### ISSUE TITLE
Create `brew` Formula

### ISSUE THREAD

**Issue by Kfeavel** [genonullfree/teleport#42]
It would be nice to have `teleport` be a formula available for installation through `brew`. The [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook) documents how to get started.

**Comment by Kfeavel** [comment]
Turns out that according to the [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) guide, a new `homebrew-teleport` repo would be required. Not sure if that's something you'd want to pursue, but it's more of a process than I initially thought.

**Comment by genonullfree** [comment]
The current recommendation is to use `cargo teleporter install` to build and install the latest.

Closing
