### ISSUE TITLE
File transfer not working

### ISSUE THREAD

**Issue by 4ndrewchin** [genonullfree/teleport#56]
Version: `0.5.3.0`

Sending an 82 byte file (no overwrite) created an empty file on the server. Data appeared to be transferred according to the client output:
```
Sending file 1/1: "file"
 =>    82.000B of   82.000B (100.00%) done!
```
82 byte file on the server is just all zeroes. Documenting this for future investigation

**Comment by genonullfree** [comment]
I did notice you mentioned `v0.5.3`, this does not seem to be an issue on the latest `v0.5.5`, but I am curious too what could be going on here

**Comment by genonullfree** [comment]
Checked out `v0.5.3` but can't seem to reproduce the issue. (Maybe I derped something up when compiling that one specifically?) Does it work for larger files, or is everything zeroes?

**Comment by 4ndrewchin** [comment]
I can't reproduce it either. I'll have to see what was up tomorrow :frowning_face:

Unfortunately, I didn't test it on any other file. Encountered the issue and immediately logged it. It could just be operator error.

**Comment by 4ndrewchin** [comment]
Issue was unrelated to teleporter. Dev machine was just in a bad state.
