### ISSUE TITLE
Allow sending files to destinations with absolute paths

### ISSUE THREAD

**Issue by GreenMobius** [genonullfree/teleport#58]
My use case for teleport is going to be using it programmatically for some system testing-

It would be really nice to be able to keep the preceding slash e.g. `/tmp/file` when transferring something, as I have some files that may use local paths from the testing directory, and some files that use absolute paths for some configuration changes.

Essentially, would it be possible to find a way to allow absolute path transfers without needing a command-line flag?

**Comment by genonullfree** [comment]
This should be relatively easy, we could disable the removal of any `/` at the beginning of the filename path in the client, and on the server side have a flag to disable the check for the beginning `/`. Could add a command argument like `--allow-absolute` when starting the server to disable the check.
