### ISSUE TITLE
Dramatic increase in time for hashing (delta overwrite) on MacOS

### ISSUE THREAD

**Issue by genonullfree** [genonullfree/teleport#61]
Perform some binary profiling to determine exact case of slowdown.

Affected versions: `v0.6.0`, `v0.5.5`, suspect the following culprits:

- blake3 on MacOS or M1
- MacOS caching

Ex Linux machine orig:
```
 =>  666.433M of  666.433M (100.00%) done! Time: 37.06s Speed: 144.094 Mbps
```
Linux machine delta overwrite:
```
 done! Time: 1.18s Speed: 3530.437 Mbps
```

Ex MacOS machine (M1Max) orig:
```
 =>    1.145G of    1.145G (100.00%) done! Time: 19.52s Speed: 493.502 Mbps
```
MacOS machine (M1Max) delta overwrite:
```
 done! Time: 84.77s Speed: 111.626 Mbps
```

**Comment by genonullfree** [comment]
At a glance, it seems that Blake3 is highly optimized for intel x86, seems us

**Comment by genonullfree** [comment]
Swapping out Blake3 for AHasher yields the following differences:

Aarch64:
`Time: 84.91s Speed: 111.626 Mbps` => `Time: 7.82s Speed: 1339.507 Mbps`
~12x as fast

x86_64:
`Time: 1.95s Speed: 5331.465 Mbps` => `Time: 9.28s Speed: 592.385 Mbps`
~0.111x as slow

As sad as those stats are for x86_64, I think it does bring a bit more parity to other architecture speeds....

**Comment by genonullfree** [comment]
Ok, doing a new comment for the `--release` versions (thanks @wcampbell0x2a !)

**Aarch64**:
Blake3 == `Time: 3.14s Speed: 3125.516 Mbps` (current default)
AHash == `Time: 252.15ms Speed: inf Mbps`
FxHash == `Time: 575.60ms Speed: inf Mbps`
xxHash == `Time: 254.68ms Speed: inf Mbps`

**x86_64**:
Blake3 == `Time: 1.08s Speed: 5331.465 Mbps`
AHash == `Time: 342.29ms Speed: inf Mbps`
FxHash == `Time: 511.00ms Speed: inf Mbps`
xxHash == `Time: 372.59ms Speed: inf Mbps`

I like how the code gets cleaned up for AHash/FxHash/xxHash, so I'll probably end up merging in AHash, but that'll cause another minor version bump, oops.

**Comment by Cyan4973** [comment]
If collision ratios of hash functions matters to you, you might want to have a look at [this comparison exercise](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison#testing-64-bit-hashes-on-small-inputs-) .

**Comment by genonullfree** [comment]
@Cyan4973 Yes it does! I would certainly like my file transfer utility to not have to really worry about hash collisions when possible. Thank you for commenting, your link is a great resource that I missed earlier.
