### ISSUE TITLE
add instructions for cross compiling

### ISSUE THREAD

**Issue by genonullfree** [genonullfree/teleport#75]
Add instructions for offline cross-compiling to various architectures.
At least supporting:

- x86
- aarch64
- arm32
- mips

With either being able to support various glibc versions or static musl builds.

**Comment by wcampbell0x2a** [comment]
The `cross` project by the rust-embedded team works wonderfully for this. I use this in `radar` for generating ARM binaries.
Simple as:
```
cross build --target armv7-unknown-linux-gnueabihf
```

**Comment by genonullfree** [comment]
This is indeed awesome, and what I came across too. However the current need is for offline cross compiling. So if using the `cross` project is the best option, instructions are needed to download the necessary docker images that you wish to target and then upload them and validate that all works and then document it. I've also updated the ticket since there was 0 info in the description.

**Comment by genonullfree** [comment]
I've had good luck using: https://github.com/messense/cargo-zigbuild
🎊 

See that repo for cross compiling instructions.
